# Generated by Django 2.1.2 on 2019-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(null=True, to='novel.Chapter'),
        ),
    ]
