# Generated by Django 2.1.2 on 2019-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20190308_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='novel.Chapter'),
        ),
    ]
